all_geos = [
["United States","","","NA"],
["Canada","","","NA"],
["Afghanistan","","","APAC"],
["Albania","","","EMEA"],
["Algeria","","","EMEA"],
["Andorra","","","EMEA"],
["Angola","","","EMEA"],
["Anguilla","","","Americas"],
["Antarctica","","","APAC"],
["Antigua and Barbuda","","","Americas"],
["Argentina","","","Americas"],
["Armenia","","","EMEA"],
["Aruba","","","Americas"],
["Australia","","","APAC"],
["Austria","","","EMEA"],
["Azerbaijan","","","APAC"],
["Bahamas","","","Americas"],
["Bahrain","","","EMEA"],
["Bangladesh","","","APAC"],
["Barbados","","","Americas"],
["Belarus","","","EMEA"],
["Belgium","","","EMEA"],
["Belize","","","Americas"],
["Benin","","","EMEA"],
["Bermuda","","","Americas"],
["Bhutan","","","APAC"],
["Bonaire, Sint Eustatius and Saba","","","Americas"],
["Bosnia and Herzegovina","","","EMEA"],
["Botswana","","","EMEA"],
["Bouvet Island","","","EMEA"],
["Brazil","","","Americas"],
["British Indian Ocean Territory","","","APAC"],
["Virgin Islands, British","","","Americas"],
["Brunei Darussalam","","","APAC"],
["Bulgaria","","","EMEA"],
["Burkina Faso","","","EMEA"],
["Burundi","","","EMEA"],
["Cambodia","","","APAC"],
["Cameroon","","","EMEA"],
["Cape Verde","","","EMEA"],
["Cayman Islands","","","Americas"],
["NA Central African Republic","","","EMEA"],
["Chad","","","EMEA"],
["Chile","","","Americas"],
["China","","","APAC"],
["Christmas Island","","","APAC"],
["Cocos (Keeling) Islands","","","APAC"],
["Colombia","","","Americas"],
["Comoros","","","EMEA"],
["Congo, the Democratic Republic of the","","","EMEA"],
["Cook Islands","","","APAC"],
["Costa Rica","","","Americas"],
["Croatia","","","EMEA"],
["Cuba","","","Americas"],
["Cyprus","","","EMEA"],
["Czech Republic","","","EMEA"],
["Cote d’Ivoire","","","EMEA"],
["Denmark","","","EMEA"],
["Djibouti","","","EMEA"],
["Dominica","","","Americas"],
["Dominican Republic","","","Americas"],
["Ecuador","","","Americas"],
["Egypt","","","EMEA"],
["El Salvador","","","Americas"],
["Equatorial Guinea","","","EMEA"],
["Eritrea","","","EMEA"],
["Estonia","","","EMEA"],
["Ethiopia","","","EMEA"],
["Falkland Islands (Malvinas)","","","APAC"],
["Faroe Islands","","","EMEA"],
["Fiji","","","APAC"],
["Finland","","","EMEA"],
["France","","","EMEA"],
["French Guiana","","","Americas"],
["French Polynesia","","","APAC"],
["French Southern Territories","","","APAC"],
["Gabon","","","EMEA"],
["Gambia","","","EMEA"],
["Georgia","","","EMEA"],
["Germany","","","EMEA"],
["Ghana","","","EMEA"],
["Gibraltar","","","EMEA"],
["Greece","","","EMEA"],
["Greenland","","","EMEA"],
["Grenada","","","Americas"],
["Guadeloupe","","","Americas"],
["Guatemala","","","Americas"],
["Guinea","","","EMEA"],
["Guinea-Bissau","","","EMEA"],
["Guyana","","","Americas"],
["Haiti","","","Americas"],
["Heard Island and McDonald Islands","","","APAC"],
["Honduras","","","Americas"],
["Hungary","","","EMEA"],
["Iceland","","","EMEA"],
["India","","","APAC"],
["Indonesia","","","APAC"],
["Iran, Islamic Republic of","","","EMEA"],
["Iraq","","","EMEA"],
["Ireland","","","EMEA"],
["Israel","","","EMEA"],
["Italy","","","EMEA"],
["Jamaica","","","Americas"],
["Japan","","","APAC"],
["Jordan","","","EMEA"],
["Kazakhstan","","","APAC"],
["Kenya","","","EMEA"],
["Kiribati","","","APAC"],
["Kuwait","","","EMEA"],
["Kyrgyzstan","","","APAC"],
["Lao People's Democratic Republic","","","APAC"],
["Latvia","","","EMEA"],
["Lebanon","","","EMEA"],
["Lesotho","","","EMEA"],
["Liberia","","","EMEA"],
["Libyan Arab Jamahiriya","","","EMEA"],
["Liechtenstein","","","EMEA"],
["Lithuania","","","EMEA"],
["Luxembourg","","","EMEA"],
["Macao","","","APAC"],
["Madagascar","","","EMEA"],
["Malawi","","","EMEA"],
["Malaysia","","","APAC"],
["Maldives","","","APAC"],
["Mali","","","EMEA"],
["Malta","","","EMEA"],
["Martinique","","","Americas"],
["Mauritania","","","EMEA"],
["Mauritius","","","EMEA"],
["Mayotte","","","EMEA"],
["Mexico","","","Americas"],
["Moldova, Republic of","","","EMEA"],
["Monaco","","","EMEA"],
["Mongolia","","","APAC"],
["Montserrat","","","Americas"],
["Morocco","","","EMEA"],
["Mozambique","","","EMEA"],
["Myanmar","","","APAC"],
["Namibia","","","EMEA"],
["Nauru","","","APAC"],
["Nepal","","","APAC"],
["Netherlands","","","EMEA"],
["New Caledonia","","","APAC"],
["New Zealand","","","APAC"],
["Nicaragua","","","Americas"],
["Niger","","","EMEA"],
["Nigeria","","","EMEA"],
["Niue","","","APAC"],
["Norfolk Island","","","APAC"],
["Korea, Democratic People's Republic of","","","APAC"],
["Norway","","","EMEA"],
["Oman","","","EMEA"],
["Pakistan","","","APAC"],
["Palestinian Territory, Occupied","","","EMEA"],
["Panama","","","Americas"],
["Papua New Guinea","","","EMEA"],
["Paraguay","","","Americas"],
["Peru","","","Americas"],
["Philippines","","","APAC"],
["Pitcairn","","","Americas"],
["Poland","","","EMEA"],
["Portugal","","","EMEA"],
["Qatar","","","EMEA"],
["Romania","","","EMEA"],
["Russian Federation","","","APAC"],
["Rwanda","","","EMEA"],
["Reunion","","","EMEA"],
["Saint Helena, Ascension and Tristan da Cunha","","","Americas"],
["Saint Kitts and Nevis","","","Americas"],
["Saint Lucia","","","Americas"],
["Saint Pierre and Miquelon","","","Americas"],
["Saint Vincent and the Grenadines","","","Americas"],
["Samoa","","","APAC"],
["San Marino","","","EMEA"],
["Sao Tome and Principe","","","EMEA"],
["Saudi Arabia","","","EMEA"],
["Senegal","","","EMEA"],
["Serbia","","","EMEA"],
["Seychelles","","","APAC"],
["Sierra Leone","","","EMEA"],
["Singapore","","","APAC"],
["Slovakia","","","EMEA"],
["Slovenia","","","EMEA"],
["Solomon Islands","","","APAC"],
["Somalia","","","EMEA"],
["South Africa","","","EMEA"],
["Korea, Republic of","","","APAC"],
["Spain","","","EMEA"],
["Sri Lanka","","","APAC"],
["Sudan","","","EMEA"],
["Suriname","","","Americas"],
["Svalbard and Jan Mayen","","","EMEA"],
["Swaziland","","","EMEA"],
["Sweden","","","EMEA"],
["Switzerland","","","EMEA"],
["Syrian Arab Republic","","","EMEA"],
["Chinese Taipei","","","APAC"],
["Tajikistan","","","APAC"],
["Tanzania, United Republic of","","","EMEA"],
["Thailand","","","APAC"],
["Timor-Leste","","","APAC"],
["Togo","","","EMEA"],
["Tokelau","","","APAC"],
["Tonga","","","APAC"],
["Trinidad and Tobago","","","Americas"],
["Turkey","","","EMEA"],
["Turkmenistan","","","APAC"],
["Turks and Caicos Islands","","","Americas"],
["Tuvalu","","","APAC"],
["Uganda","","","EMEA"],
["Ukraine","","","EMEA"],
["United Arab Emirates","","","EMEA"],
["United Kingdom","","","EMEA"],
["Uruguay","","","Americas"],
["Uzbekistan","","","APAC"],
["Vanuatu","","","APAC"],
["Vatican","","","EMEA"],
["Venezuela, Bolivarian Republic of","","","Americas"],
["Viet Nam","","","APAC"],
["Wallis and Futuna","","","APAC"],
["NA Western Sahara","","","EMEA"],
["Yemen","","","EMEA"],
["Yugoslavia","","","EMEA"],
["Zambia","","","EMEA"],
["Zimbabwe","","","EMEA"],
["Aland Islands","","","EMEA"],
["Saint Barthélemy","","","Americas"],
["Bolivia, Plurinational State of","","","Americas"],
["Curaçao","","","Americas"],
["Guernsey","","","EMEA"],
["South Georgia and the South Sandwich Islands","","","Americas"],
["Isle of Man","","","EMEA"],
["Jersey","","","EMEA"],
["Montenegro","","","EMEA"],
["Saint Martin (French part)","","","Americas"],
["Macedonia, the former Yugoslav Republic of","","","EMEA"],
["South Sudan","","","EMEA"],
["Sint Maarten (Dutch part)","","","Americas"],
["Tunesia","","","EMEA"],
["Holy See (Vatican City State)","","","EMEA"],
["United States","Alabama","","NA East"],
["United States","Alaska","","NA West"],
["United States","Arizona","","NA Mountain"],
["United States","Arkansas","","NA Central"],
["United States","California","","NA West"],
["United States","Colorado","","NA Mountain"],
["United States","Connecticut","","NA East"],
["United States","Delaware","","NA East"],
["United States","District of Columbia","","NA East"],
["United States","Florida","","NA East"],
["United States","Georgia","","NA East"],
["United States","Hawaii","","NA West"],
["United States","Idaho","","NA Mountain"],
["United States","Illinois","","NA Central"],
["United States","Indiana","","NA Central"],
["United States","Iowa","","NA Central"],
["United States","Kansas","","NA Central"],
["United States","Kentucky","","NA East"],
["United States","Louisiana","","NA East"],
["United States","Maine","","NA East"],
["United States","Maryland","","NA East"],
["United States","Massachusetts","","NA East"],
["United States","Michigan","","NA East"],
["United States","Minnesota","","NA Central"],
["United States","Mississippi","","NA Central"],
["United States","Missouri","","NA Central"],
["United States","Montana","","NA Mountain"],
["United States","Nebraska","","NA Central"],
["United States","Nevada","","NA West"],
["United States","New Hampshire","","NA East"],
["United States","New Jersey","","NA East"],
["United States","New Mexico","","NA Mountain"],
["United States","New York","","NA East"],
["United States","North Carolina","","NA East"],
["United States","North Dakota","","NA Mountain"],
["United States","Ohio","","NA East"],
["United States","Oklahoma","","NA Central"],
["United States","Oregon","","NA West"],
["United States","Pennsylvania","","NA East"],
["United States","Rhode Island","","NA East"],
["United States","South Carolina","","NA East"],
["United States","South Dakota","","NA Mountain"],
["United States","Tennessee","","NA East"],
["United States","Texas","","NA Central"],
["United States","Utah","","NA Mountain"],
["United States","Vermont","","NA East"],
["United States","Virginia","","NA East"],
["United States","Washington","","NA West"],
["United States","NA West Virginia","","NA East"],
["United States","Wisconsin","","NA Central"],
["Canada","Alberta","","NA Mountain"],
["Canada","British Columbia","","NA West"],
["Canada","Manitoba","","NA Central"],
["Canada","New Brunswick","","NA East"],
["Canada","Newfoundland and Labrador","","NA East"],
["Canada","Nova Scotia","","NA East"],
["Canada","Ontario","","NA East"],
["Canada","Prince Edward Island","","NA East"],
["Canada","Quebec","","NA East"],
["United States","California","94062","NA West"]
]

all_geos.each do |geo|
	Geo.create(country: geo[0], sub_country: geo[1], zip_code: geo[2], area: geo[3], routing_type: 'geographic')
end

all_letters = ['']
('a'..'z').each { |letter| all_letters << letter }

all_letters.each do |geo|
	Geo.create(starting_letter: geo, routing_type: 'alphabetical')
end


User.create(email: 'casey@twilio.com', password: 'password')
User.create(email: 'nick@twilio.com', password: 'twilio098')
User.create(email: 'emerald@twilio.com', password: 'twilio098')


